baseURL = "https://guhan62.github.io/"
languageCode = "en-us"
title = "guhan.me"
theme = "shadow"

pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true

staticDir = ["static"]

[taxonomies]
  category = "categories"

# Social Accounts
[params.social]
    [[params.social.github]]
        media = "github"
        uname = "guhan62"
        link = "https://github.com/guhan62"
    [[params.social.twitter]]
        media = "twitter"
        uname = "guen2"
        link = "https://twitter.com/guen2"
    [[params.social.linkedin]]
        media = "linkedin"
        uname = "guhan62"
        link = "https://www.linkedin.com/in/guhan-me/"
[menu]
    [[menu.main]]
        name = "About"
        url = "about/"
        weight = 20

    [[menu.main]]
        name = "Blog"
        url = "blogs/"
        weight = 10

    [[menu.main]]
        name = "CV"
        url = "https://drive.google.com/file/d/1p18D6XH9fXTklWO-iM9FCUJufeTFf1MJ/view?usp=sharing"
        weight = 10

    [[menu.main]]
        name = "Reads"
        url = "reads/"
        weight = 10

    [[menu.main]]
        name = "Portfolio"
        url = "portfolio/"
        weight = 10

    [[menu.main]]
        name = "Coursework"
        url = "courses/"
        weight = 10